/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * APRSInfoDialog.java
 *
 * Created on 13.05.2009, 14:28:03
 */

package javapskmail;

/**
 *
 * @author sebastian_pohl
 */
public class APRSInfoDialog extends javax.swing.JDialog {

    mainpskmaillogic pskmaillogic;

    /** Creates new form APRSInfoDialog */
    public APRSInfoDialog(mainpskmaillogic parentlogic, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pskmaillogic = parentlogic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGetAPRSmsg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnGetGrib = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnGetAPRSstation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGetTidestations = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnGetTide = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTableNumber = new javax.swing.JTextField();
        btnGetCamperSites = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnGetServerFreq = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnGetPSKmailNews = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/APRSInfoDialog"); // NOI18N
        jLabel1.setText(bundle.getString("GET_APRS_INFO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setText(bundle.getString("PUSH_MESSAGE_BUTTONS_TO_SEND_REQUEST_...")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        btnGetAPRSmsg.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetAPRSmsg.setText(bundle.getString("PAGE_1")); // NOI18N
        btnGetAPRSmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAPRSmsgActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetAPRSmsg, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel6.setText(bundle.getString("GET_APRS_MESSAGES")); // NOI18N
        jLabel6.setToolTipText(bundle.getString("RUFT_KURZ-EMAIL_UND_APRS_MESSAGEN_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel6, gridBagConstraints);

        btnGetGrib.setText(bundle.getString("PAGE_2")); // NOI18N
        btnGetGrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGribActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetGrib, gridBagConstraints);

        jLabel10.setText(bundle.getString("GET_GRIB_FILE")); // NOI18N
        jLabel10.setToolTipText(bundle.getString("RUFT_GRIB_DATEN_UM_DEINE_POSITION_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel10, gridBagConstraints);

        btnGetAPRSstation.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetAPRSstation.setText(bundle.getString("PAGE_3")); // NOI18N
        btnGetAPRSstation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAPRSstationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetAPRSstation, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setText(bundle.getString("GET_APRS_STATION_NEAR_YOU")); // NOI18N
        jLabel5.setToolTipText(bundle.getString("RUFT_APRS_NACHBARSTATIONEN_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        btnGetTidestations.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetTidestations.setText(bundle.getString("PAGE_4")); // NOI18N
        btnGetTidestations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTidestationsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetTidestations, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText(bundle.getString("GET_TIDE_STATIONS")); // NOI18N
        jLabel3.setToolTipText(bundle.getString("RUFT_TIDENSTATION_UM_DEINE_POSITION_HERUM_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        btnGetTide.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetTide.setText(bundle.getString("PAGE_5")); // NOI18N
        btnGetTide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetTide, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText(bundle.getString("GET_TIDE_(TABLE_NR.)")); // NOI18N
        jLabel4.setToolTipText(bundle.getString("RUFT_EINE_BESTIMMTE_(NUMMER_IN_SENDEZEILE)_TIDEN-STATION_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtTableNumber.setText(bundle.getString("APRSInfoDialog.txtTableNumber.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanel1.add(txtTableNumber, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        btnGetCamperSites.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetCamperSites.setText(bundle.getString("PAGE_6")); // NOI18N
        btnGetCamperSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCamperSitesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetCamperSites, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText(bundle.getString("GET_CAMPER_SITES")); // NOI18N
        jLabel7.setToolTipText(bundle.getString("RUFT_CAMPINGPLÄTZE_UM_DEINE_POSITION_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel7, gridBagConstraints);

        btnGetServerFreq.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetServerFreq.setText(bundle.getString("PAGE_7")); // NOI18N
        btnGetServerFreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetServerFreqActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetServerFreq, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel8.setText(bundle.getString("GET_SERVERFREQS")); // NOI18N
        jLabel8.setToolTipText(bundle.getString("RUFT_PSKMAIL_SERVERFREQUENZEN_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel8, gridBagConstraints);

        btnGetPSKmailNews.setFont(new java.awt.Font("Arial", 0, 11));
        btnGetPSKmailNews.setText(bundle.getString("PAGE_8")); // NOI18N
        btnGetPSKmailNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPSKmailNewsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        getContentPane().add(btnGetPSKmailNews, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel9.setText(bundle.getString("GET_PSKMAIL_NEWS")); // NOI18N
        jLabel9.setToolTipText(bundle.getString("RUFT_PSKMAIL_NEWS_AB.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel9, gridBagConstraints);

        jButton1.setText(bundle.getString("CANCEL")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetPSKmailNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPSKmailNewsActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetPskmailNewsActionPerformed(evt);
}//GEN-LAST:event_btnGetPSKmailNewsActionPerformed

    private void btnGetServerFreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetServerFreqActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetServerfqActionPerformed(evt);
}//GEN-LAST:event_btnGetServerFreqActionPerformed

    private void btnGetAPRSmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAPRSmsgActionPerformed
        // TODO add your handling code here:
        pskmaillogic.menuMessagesActionPerformed(evt);
}//GEN-LAST:event_btnGetAPRSmsgActionPerformed

    private void btnGetAPRSstationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAPRSstationActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetAPRSActionPerformed(evt);
}//GEN-LAST:event_btnGetAPRSstationActionPerformed

    private void btnGetTideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTideActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetTideActionPerformed(evt);
}//GEN-LAST:event_btnGetTideActionPerformed

    private void btnGetTidestationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTidestationsActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetTidestationsActionPerformed(evt);
}//GEN-LAST:event_btnGetTidestationsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGetGribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGribActionPerformed
        // TODO add your handling code here:
        pskmaillogic.GetGribActionPerformed(evt);
    }//GEN-LAST:event_btnGetGribActionPerformed

    private void btnGetCamperSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCamperSitesActionPerformed
        // TODO add your handling code here:
        pskmaillogic.mnuGetCamperActionPerformed(evt);
    }//GEN-LAST:event_btnGetCamperSitesActionPerformed

    public String getTableNumber() {
        return txtTableNumber.getText();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                APRSInfoDialog dialog = new APRSInfoDialog(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetAPRSmsg;
    private javax.swing.JButton btnGetAPRSstation;
    private javax.swing.JButton btnGetCamperSites;
    private javax.swing.JButton btnGetGrib;
    private javax.swing.JButton btnGetPSKmailNews;
    private javax.swing.JButton btnGetServerFreq;
    private javax.swing.JButton btnGetTide;
    private javax.swing.JButton btnGetTidestations;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTableNumber;
    // End of variables declaration//GEN-END:variables

}
