/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmailOptionDialog.java
 *
 * Created on 14.05.2009, 08:19:47
 */

package javapskmail;

/**
 *
 * @author sebastian_pohl
 */
public class EmailOptionDialog extends javax.swing.JDialog {

    /** Creates new form EmailOptionDialog */
    public EmailOptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmailOK = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtReplyTo = new javax.swing.JTextField();
        txtPopPassword = new javax.swing.JTextField();
        txtPopUser = new javax.swing.JTextField();
        txtPopHost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/EmailOptionDialog"); // NOI18N
        jLabel1.setText(bundle.getString("EMAIL_OPTIONS")); // NOI18N

        btnEmailOK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEmailOK.setText(bundle.getString("OK")); // NOI18N
        btnEmailOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailOKActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 16));
        jButton1.setText(bundle.getString("EXAMPLE")); // NOI18N
        jButton1.setEnabled(false);

        txtReplyTo.setFont(new java.awt.Font("Arial", 0, 16));
        txtReplyTo.setToolTipText(bundle.getString("DEINE_ZWEITE_(ERSATZ-)EMAILADDRESSE.")); // NOI18N

        txtPopPassword.setFont(new java.awt.Font("Arial", 0, 16));
        txtPopPassword.setToolTipText(bundle.getString("DEIN_PASSWORT_VOM_PROVIDERZUGANG_EINTRAGEN.")); // NOI18N

        txtPopUser.setFont(new java.awt.Font("Arial", 0, 16));
        txtPopUser.setToolTipText(bundle.getString("DEINE_EMAILADDRESSE_EINTRAGEN.")); // NOI18N

        txtPopHost.setFont(new java.awt.Font("Arial", 0, 16));
        txtPopHost.setToolTipText(bundle.getString("BITTE_POPSERVER_DEINES_EMAIL-PROVIDERS_EINTRAGEN.")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel5.setText(bundle.getString("REPLY_TO")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel4.setText(bundle.getString("POP_PASSWORD")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel3.setText(bundle.getString("POP_USER")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel2.setText(bundle.getString("POP_HOST")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtReplyTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtPopPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtPopUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtPopHost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(btnEmailOK, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReplyTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmailOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmailOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
}//GEN-LAST:event_btnEmailOKActionPerformed

    public void setPopHost(String str) {
        this.txtPopHost.setText(str);
    }

    public String getPopHost() {
        return this.txtPopHost.getText();
    }

    public void setPopPassword(String str) {
        this.txtPopPassword.setText(str);
    }

    public String getPopPassword() {
        return this.txtPopPassword.getText();
    }

    public void setPopUser(String str) {
        this.txtPopUser.setText(str);
    }

    public String getPopUser() {
        return this.txtPopUser.getText();
    }

    public void setReplyTo(String str) {
        this.txtReplyTo.setText(str);
    }

    public String getReplyTo() {
        return this.txtReplyTo.getText();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmailOptionDialog dialog = new EmailOptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmailOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPopHost;
    private javax.swing.JTextField txtPopPassword;
    private javax.swing.JTextField txtPopUser;
    private javax.swing.JTextField txtReplyTo;
    // End of variables declaration//GEN-END:variables

}
