/*
 * GetWebPageDialog.java
 *
 * Created on March 17, 2009, 3:40 PM
 */

package javapskmail;

/**
 *
 * @author  rein
 */
public class GetWebPageDialog extends javax.swing.JDialog {
    arq myarq;

    /** Creates new form GetWebPageDialog */
    public GetWebPageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myarq = new arq();

        
        this.WebPage1.setText(Main.configuration.getPreference("URL1"));
         this.WebPage2.setText(Main.configuration.getPreference("URL2"));
         this.WebPage3.setText(Main.configuration.getPreference("URL3"));
         this.WebPage4.setText(Main.configuration.getPreference("URL4"));
         this.WebPage5.setText(Main.configuration.getPreference("URL5"));
         this.WebPage6.setText(Main.configuration.getPreference("URL6"));
         this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        WebPage1 = new javax.swing.JTextField();
        WebPage2 = new javax.swing.JTextField();
        WebPage3 = new javax.swing.JTextField();
        WebPage4 = new javax.swing.JTextField();
        WebPage5 = new javax.swing.JTextField();
        WebPage6 = new javax.swing.JTextField();
        WebButton1 = new javax.swing.JButton();
        WebButton2 = new javax.swing.JButton();
        WebButton3 = new javax.swing.JButton();
        WebButton4 = new javax.swing.JButton();
        WebButton5 = new javax.swing.JButton();
        WebButton6 = new javax.swing.JButton();
        Weblabel = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        WebOKButton = new javax.swing.JButton();
        GetWebCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(325, 286));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        WebPage1.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage1.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage1, gridBagConstraints);

        WebPage2.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage2.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage2, gridBagConstraints);

        WebPage3.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage3.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage3, gridBagConstraints);

        WebPage4.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage4.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage4, gridBagConstraints);

        WebPage5.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage5.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage5, gridBagConstraints);

        WebPage6.setMinimumSize(new java.awt.Dimension(250, 27));
        WebPage6.setPreferredSize(new java.awt.Dimension(250, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebPage6, gridBagConstraints);

        WebButton1.setText("URL 1");
        WebButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton1, gridBagConstraints);

        WebButton2.setText("URL 2");
        WebButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton2, gridBagConstraints);

        WebButton3.setText("URL 3");
        WebButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton3, gridBagConstraints);

        WebButton4.setText("URL 4");
        WebButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton4, gridBagConstraints);

        WebButton5.setText("URL 5");
        WebButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton5, gridBagConstraints);

        WebButton6.setText("URL 6");
        WebButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(WebButton6, gridBagConstraints);

        Weblabel.setFont(new java.awt.Font("Dialog", 1, 14));
        Weblabel.setText("Get URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(Weblabel, gridBagConstraints);

        getContentPane().add(jPanel1);

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        WebOKButton.setText("OK");
        WebOKButton.setMinimumSize(new java.awt.Dimension(80, 30));
        WebOKButton.setPreferredSize(new java.awt.Dimension(80, 30));
        WebOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebOKButtonActionPerformed(evt);
            }
        });
        pnlButtons.add(WebOKButton);

        GetWebCancelButton.setText("Cancel");
        GetWebCancelButton.setMinimumSize(new java.awt.Dimension(80, 30));
        GetWebCancelButton.setPreferredSize(new java.awt.Dimension(80, 30));
        GetWebCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetWebCancelButtonActionPerformed(evt);
            }
        });
        pnlButtons.add(GetWebCancelButton);

        getContentPane().add(pnlButtons);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetWebCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetWebCancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_GetWebCancelButtonActionPerformed

    private void WebOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebOKButtonActionPerformed
        // TODO add your handling code here:
        String path = Main.HomePath + Main.Dirprefix;
        config c = new config(path);
        c.SetWebPages(WebPage1.getText(), WebPage2.getText(), WebPage3.getText(), WebPage4.getText(), WebPage5.getText(), WebPage6.getText());
        c.saveURLs();
    }//GEN-LAST:event_WebOKButtonActionPerformed

    private void WebButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton1ActionPerformed
        // TODO add your handling code here:
        if (Main.Connected){
            if (this.WebPage1.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage1.getText() + "\n";
            }
        } else {
             myarq.Message("You need to connect first...", 5);
        }
         this.setVisible(false);
    }//GEN-LAST:event_WebButton1ActionPerformed

    private void WebButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton2ActionPerformed
        // TODO add your handling code here:
        if (Main.Connected) {
            if (this.WebPage2.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage2.getText() + "\n";
            }   
        } else {
            myarq.Message("You need to connect first...", 5);
        }
         this.setVisible(false);
    }//GEN-LAST:event_WebButton2ActionPerformed

    private void WebButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton3ActionPerformed
        // TODO add your handling code here
        if (Main.Connected) {
            if (this.WebPage3.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage3.getText() + "\n";
            }  
        } else {
            myarq.Message("You need to connect first...", 5);
        }
         this.setVisible(false);
    }//GEN-LAST:event_WebButton3ActionPerformed

    private void WebButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton4ActionPerformed
        // TODO add your handling code here:
        if (Main.Connected) {
            if (this.WebPage4.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage4.getText() + "\n";
            }   
        } else {
               myarq.Message("You need to connect first...", 5);
           }
          this.setVisible(false);
    }//GEN-LAST:event_WebButton4ActionPerformed

    private void WebButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton5ActionPerformed
        // TODO add your handling code here:
        if (Main.Connected) {
            if (this.WebPage5.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage5.getText() + "\n";
            }  
        } else {
            myarq.Message("You need to connect first...", 5);
        }
         this.setVisible(false);
    }//GEN-LAST:event_WebButton5ActionPerformed

    private void WebButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebButton6ActionPerformed
        // TODO add your handling code here:
        if (Main.Connected) {
            if (this.WebPage6.getText().length() > 0){
                Main.TX_Text += "~TGET " + this.WebPage6.getText() + "\n";
            } 
        } else {
            myarq.Message("You need to connect first...", 5);
        }
         this.setVisible(false);
    }//GEN-LAST:event_WebButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GetWebPageDialog dialog = new GetWebPageDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                   
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetWebCancelButton;
    private javax.swing.JButton WebButton1;
    private javax.swing.JButton WebButton2;
    private javax.swing.JButton WebButton3;
    private javax.swing.JButton WebButton4;
    private javax.swing.JButton WebButton5;
    private javax.swing.JButton WebButton6;
    private javax.swing.JButton WebOKButton;
    private javax.swing.JTextField WebPage1;
    private javax.swing.JTextField WebPage2;
    private javax.swing.JTextField WebPage3;
    private javax.swing.JTextField WebPage4;
    private javax.swing.JTextField WebPage5;
    private javax.swing.JTextField WebPage6;
    private javax.swing.JLabel Weblabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlButtons;
    // End of variables declaration//GEN-END:variables
    
}
