/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GPSOptionDialog.java
 *
 * Created on 22.06.2009, 13:39:20
 */

package javapskmail;

/**
 *
 * @author sebastian_pohl
 */
public class GPSOptionDialog extends javax.swing.JDialog {

    /** Creates new form GPSOptionDialog */
    public GPSOptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setGPSconnected(boolean b) {
        this.chkGPSconnected.setSelected(b);
    }

    public boolean getGPSconnected() {
        return this.chkGPSconnected.isSelected();
    }

    public void removeAllItemsGPSSerialPort() {
        this.cboSerialPort.removeAllItems();
    }

    public void removeAllItemsGPSSpeed() {
        this.cboSpeed.removeAllItems();
    }

    public void addItemGPSSerialPort(Object o) {
        this.cboSerialPort.addItem(o);
    }

    public void addItemGPSSpeed(Object o) {
        this.cboSpeed.addItem(o);
    }

    public void setSelectedGPSSerialPort(Object o) {
        this.cboSerialPort.setSelectedItem(o);
    }

    public void setSelectedGPSSpeed(Object o) {
        this.cboSpeed.setSelectedItem(o);
    }

    public Object getSelectedGPSSerialPort() {
        return this.cboSerialPort.getSelectedItem();
    }

    public Object getSelectedGPSSpeed() {
        return this.cboSpeed.getSelectedItem();
    }

    public void setEnabledGPSSerialPort(boolean b) {
        this.cboSerialPort.setEnabled(b);
    }

    public void setEnabledGPSSpeed(boolean b) {
        this.cboSpeed.setEnabled(b);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkGPSconnected = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboSerialPort = new javax.swing.JComboBox();
        cboSpeed = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/GPSOptionDialog"); // NOI18N
        jLabel1.setText(bundle.getString("GPS_OPTIONS")); // NOI18N

        chkGPSconnected.setFont(new java.awt.Font("Arial", 0, 16));
        chkGPSconnected.setText(bundle.getString("GPS_IS_CONNECTED")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel2.setText(bundle.getString("SERIAL_PORT")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel3.setText(bundle.getString("SPEED")); // NOI18N

        cboSerialPort.setFont(new java.awt.Font("Arial", 0, 16));
        cboSerialPort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSerialPort.setToolTipText(bundle.getString("PORTNUMMER_DES_GPS-GERÄTS_(SIEHE_SYSTEMSTEUERUNG_UNTER_WINDOWS)")); // NOI18N

        cboSpeed.setFont(new java.awt.Font("Arial", 0, 16));
        cboSpeed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1200", "2400", "4800", "9600", "19200" }));
        cboSpeed.setToolTipText(bundle.getString("GESCHWINDIGKEIT_DES_GPS_PORTS.")); // NOI18N

        btnOK.setFont(new java.awt.Font("Arial", 0, 16));
        btnOK.setText(bundle.getString("OK")); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkGPSconnected)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSpeed, 0, 140, Short.MAX_VALUE)
                            .addComponent(cboSerialPort, 0, 140, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkGPSconnected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(cboSerialPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cboSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GPSOptionDialog dialog = new GPSOptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cboSerialPort;
    private javax.swing.JComboBox cboSpeed;
    private javax.swing.JCheckBox chkGPSconnected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
