/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MetareaPanel.java
 *
 * Created on 29.12.2009, 09:53:10
 */

package javapskmail;

import javax.swing.JFrame;

/**
 *
 * @author sebastian_pohl
 */
public class MetareaPanel extends javax.swing.JFrame {

    /** Creates new form MetareaPanel */
    public MetareaPanel(Integer number, String report) {
        initComponents();

        if (number == 17)
            number = 8;

        if (number == 18)
            number = 3;

        this.setTitle("Metarea " + number);

        jTextArea1.setText(report);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new java.awt.GridLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetareaPanel(1, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
