/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OperatorOptionDialog.java
 *
 * Created on 14.05.2009, 08:23:01
 */

package javapskmail;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author sebastian_pohl
 */
public class OperatorOptionDialog extends javax.swing.JDialog {

    final JFileChooser fc = new JFileChooser();

    private boolean newsGroupEnabled = false;

    /** Creates new form OperatorOptionDialog */
    public OperatorOptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        chkNewsGroup.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.DESELECTED) {
                    newsGroupEnabled = false;
                }
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    newsGroupEnabled = true;
                }
            }

        });
    }

    public void setCallsign(String str) {
        this.txtCallsign.setText(str);
    }

    public String getCallsign() {
        return this.txtCallsign.getText();
    }

    public void setBlockLength(String str) {
        this.txtBlockLength.setText(str);
    }

    public String getBlockLength() {
        return this.txtBlockLength.getText();
    }

    public void setOperatorName(String str) {
        this.txtOperatorName.setText(str);
    }

    public String getOperatorName() {
        return this.txtOperatorName.getText();
    }

    public void setPictureName(String str) {
        this.txtPictureName.setText(str);
    }

    public String getPictureName() {
        return this.txtPictureName.getText();
    }

    public void setPicturePath(String str) {
        this.txtPicturePath.setText(str);
    }

    public String getPicturePath() {
        return this.txtPicturePath.getText();
    }

    public void setNewsgroup(String str) {
        this.txtNewsGroup.setText(str);
    }

    public String getNewsgroup() {
        return this.txtNewsGroup.getText();
    }

    public void setNewsgroupenabled(String str) {
        if (str.equals("true")) {
            chkNewsGroup.setSelected(true);
        } else {
            chkNewsGroup.setSelected(false);
        }
    }

    public String getNewsgroupenabled() {
        if (newsGroupEnabled) {
            return "true";
        } else {
            return "false";
        }
    }

    public void setAPRSIcon(String str) {
        this.cboAPRSIcon.setSelectedItem(str);
    }

    public String getAPRSIcon() {
        return (String) this.cboAPRSIcon.getSelectedItem();
    }

    public void setPosTime(String str) {
        this.cboPosTime.setSelectedItem(str);
    }

    public String getPosTime() {
        return (String) this.cboPosTime.getSelectedItem();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBlockLength = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCallsign = new javax.swing.JTextField();
        cboAPRSIcon = new javax.swing.JComboBox();
        cboPosTime = new javax.swing.JComboBox();
        txtOperatorName = new javax.swing.JTextField();
        txtPicturePath = new javax.swing.JTextField();
        txtPictureName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchPicture = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnIconList = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnOperatorOK = new javax.swing.JButton();
        txtNewsGroup = new javax.swing.JTextField();
        chkNewsGroup = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBlockLength.setEditable(false);
        txtBlockLength.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/OperatorOptionDialog"); // NOI18N
        txtBlockLength.setToolTipText(bundle.getString("BITTE_VORGEGEBENE_EINSTELLUNG_BEIBEHALTEN,_ANSONSTEN_OHNE_GEWÄHR.")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText(bundle.getString("OPERATOR_OPTION")); // NOI18N

        txtCallsign.setFont(new java.awt.Font("Arial", 0, 16));

        cboAPRSIcon.setEditable(true);
        cboAPRSIcon.setFont(new java.awt.Font("Arial", 0, 16));
        cboAPRSIcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "/y", "/-", "/Y", "/s", "/>", "/U", "/;", "/v" }));
        cboAPRSIcon.setToolTipText(bundle.getString("BITTE_SYMBOL_AUS_NEBENSTEHENDER_LISTE_EINTRAGEN,_SOFERN_NICHT_IN_SCROLLBALKEN_ENTHALTEN.")); // NOI18N

        cboPosTime.setFont(new java.awt.Font("Arial", 0, 16));
        cboPosTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Auto 10", "Auto 30", "Auto 60" }));
        cboPosTime.setEnabled(false);

        txtOperatorName.setFont(new java.awt.Font("Arial", 0, 16));

        txtPicturePath.setFont(new java.awt.Font("Arial", 0, 16));
        txtPicturePath.setMaximumSize(new java.awt.Dimension(140, 25));
        txtPicturePath.setMinimumSize(new java.awt.Dimension(140, 25));
        txtPicturePath.setPreferredSize(new java.awt.Dimension(140, 25));

        txtPictureName.setFont(new java.awt.Font("Arial", 0, 16));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel2.setText(bundle.getString("MY_CALL")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel4.setText(bundle.getString("POSITION_TIME")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel5.setText(bundle.getString("OPERATOR_NAME")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel7.setText(bundle.getString("PICTURE_NAME")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel6.setText(bundle.getString("BLOCK_LENGTH")); // NOI18N
        jLabel6.setToolTipText("");

        btnSearchPicture.setFont(new java.awt.Font("Arial", 0, 16));
        btnSearchPicture.setText(bundle.getString("SEARCH_PICTURE")); // NOI18N
        btnSearchPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPictureActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16));
        jLabel3.setText(bundle.getString("APRS_ICON")); // NOI18N

        btnIconList.setFont(new java.awt.Font("Arial", 0, 16));
        btnIconList.setText(bundle.getString("ICON_LIST")); // NOI18N
        btnIconList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconListActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 16));
        jButton2.setText(bundle.getString("UPLOAD")); // NOI18N
        jButton2.setEnabled(false);

        btnOperatorOK.setFont(new java.awt.Font("Arial", 0, 16));
        btnOperatorOK.setText(bundle.getString("OK")); // NOI18N
        btnOperatorOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorOKActionPerformed(evt);
            }
        });

        txtNewsGroup.setFont(new java.awt.Font("Tahoma", 0, 16));
        txtNewsGroup.setText(bundle.getString("PSKAPR")); // NOI18N
        txtNewsGroup.setEnabled(false);

        chkNewsGroup.setFont(new java.awt.Font("Tahoma", 0, 16));
        chkNewsGroup.setText(bundle.getString("NEWS_GROUP")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOperatorOK, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNewsGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtBlockLength, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCallsign, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboAPRSIcon, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboPosTime, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOperatorName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPictureName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPicturePath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIconList))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnSearchPicture)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)))
                            .addComponent(jLabel6)
                            .addComponent(chkNewsGroup))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAPRSIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnIconList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPosTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperatorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPicture)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPictureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewsGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkNewsGroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBlockLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperatorOK)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperatorOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorOKActionPerformed
        // TODO add your handling code here:
        setVisible(false);
}//GEN-LAST:event_btnOperatorOKActionPerformed

    private void btnSearchPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPictureActionPerformed
        // TODO add your handling code here:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            setPicturePath(file.getAbsolutePath());
        }
}//GEN-LAST:event_btnSearchPictureActionPerformed

    private void btnIconListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconListActionPerformed
        // TODO add your handling code here:
        try {
            Process p =
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler APRS_Symbol_Chart.pdf");
            p.waitFor();
        }
        catch(Exception e) {}
}//GEN-LAST:event_btnIconListActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OperatorOptionDialog dialog = new OperatorOptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconList;
    private javax.swing.JButton btnOperatorOK;
    private javax.swing.JButton btnSearchPicture;
    private javax.swing.JComboBox cboAPRSIcon;
    private javax.swing.JComboBox cboPosTime;
    private javax.swing.JCheckBox chkNewsGroup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBlockLength;
    private javax.swing.JTextField txtCallsign;
    private javax.swing.JTextField txtNewsGroup;
    private javax.swing.JTextField txtOperatorName;
    private javax.swing.JTextField txtPictureName;
    private javax.swing.JTextField txtPicturePath;
    // End of variables declaration//GEN-END:variables

}
