/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pskmailtrafficpanel.java
 *
 * Created on 03.03.2009, 12:59:04
 */

package javapskmail;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author sebastian_pohl
 */
public class pskmailtrafficpanel extends javax.swing.JPanel {

    mainpskmaillogic parentlogic;

    /** Creates new form pskmailtrafficpanel */
    public pskmailtrafficpanel(mainpskmaillogic currentlogic) {
        initComponents();
        parentlogic = currentlogic;

        Main.mainInput.setBox(cboMainEntry);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jProgressBar1 = new javax.swing.JProgressBar();
        pnlTraffic = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTraffic = new javax.swing.JTextArea();
        TrafficLabel = new javax.swing.JButton();
        pnlMessages = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cboMainEntry = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pnlTraffic.setBackground(new java.awt.Color(255, 255, 255));
        pnlTraffic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/pskmailtrafficpanel"); // NOI18N
        jLabel1.setText(bundle.getString("PSKMAIL_ACTION")); // NOI18N

        txtStatus.setBackground(new java.awt.Color(203, 207, 228));
        txtStatus.setFont(new java.awt.Font("Arial", 1, 13));
        txtStatus.setForeground(new java.awt.Color(204, 0, 0));
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setText(bundle.getString("CONNECTING")); // NOI18N
        txtStatus.setToolTipText(bundle.getString("INFOZEILE_FÜR_AKTIVITÄTEN_IN_DER_PROGRAMMABFOLGE.")); // NOI18N
        txtStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStatus.setOpaque(true);

        StatusLabel.setBackground(new java.awt.Color(203, 207, 228));
        StatusLabel.setFont(new java.awt.Font("Arial", 1, 13));
        StatusLabel.setForeground(new java.awt.Color(51, 51, 51));
        StatusLabel.setToolTipText(bundle.getString("TEMPORÄRE_PROGRAMMABLAUFANZEIGE_(WAS_TUT_DER_CLIENT?)")); // NOI18N
        StatusLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StatusLabel.setOpaque(true);

        txtClock.setBackground(new java.awt.Color(203, 207, 228));
        txtClock.setFont(new java.awt.Font("Arial", 1, 13));
        txtClock.setForeground(new java.awt.Color(51, 0, 255));
        txtClock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClock.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText(bundle.getString("STATION-TIME")); // NOI18N

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTraffic.setBackground(new java.awt.Color(255, 255, 204));
        txtTraffic.setColumns(20);
        txtTraffic.setEditable(false);
        txtTraffic.setFont(new java.awt.Font("Monospaced", 1, 13));
        txtTraffic.setRows(5);
        jScrollPane2.setViewportView(txtTraffic);

        TrafficLabel.setBackground(new java.awt.Color(255, 255, 255));
        TrafficLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        TrafficLabel.setText(bundle.getString("PSKMAIL_TRAFFIC")); // NOI18N
        TrafficLabel.setBorder(null);

        javax.swing.GroupLayout pnlTrafficLayout = new javax.swing.GroupLayout(pnlTraffic);
        pnlTraffic.setLayout(pnlTrafficLayout);
        pnlTrafficLayout.setHorizontalGroup(
            pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrafficLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTrafficLayout.createSequentialGroup()
                        .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTrafficLayout.createSequentialGroup()
                                .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTrafficLayout.createSequentialGroup()
                                .addComponent(txtClock, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(pnlTrafficLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrafficLayout.createSequentialGroup()
                        .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnlTrafficLayout.createSequentialGroup()
                        .addComponent(TrafficLabel)
                        .addContainerGap(462, Short.MAX_VALUE))))
        );
        pnlTrafficLayout.setVerticalGroup(
            pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrafficLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrafficLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTrafficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlTraffic, gridBagConstraints);

        pnlMessages.setBackground(new java.awt.Color(255, 255, 255));
        pnlMessages.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMessages.setPreferredSize(new java.awt.Dimension(418, 220));

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText(bundle.getString("OUTGOING-MESSAGE_/_APRS-EMAIL")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText(bundle.getString("INCOMING-MESSAGE_/_APRS-EMAIL")); // NOI18N

        jTextArea3.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setFont(new java.awt.Font("Arial", 1, 13));
        jTextArea3.setForeground(new java.awt.Color(51, 0, 204));
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText(bundle.getString("AUSGABEFELD_VON_APRS-EMAILS_UND_APRS-MESSAGEN._VORAUSSETZUNG_MAN_IST_GELINKT._(LINKTASTE,_INDICATOR_GRÜN!)")); // NOI18N
        jScrollPane1.setViewportView(jTextArea3);

        jPanel1.setBackground(new java.awt.Color(203, 207, 228));

        cboMainEntry.setEditable(true);
        cboMainEntry.setFont(new java.awt.Font("Arial", 1, 13));
        cboMainEntry.setForeground(new java.awt.Color(51, 0, 204));
        ((JTextField) cboMainEntry.getEditor().getEditorComponent()).setDocument(new JTextFieldLimit(67));
        cboMainEntry.setToolTipText(bundle.getString("EINGABE_VON_TEXTEN_FÜR:_A)_QSO_UNTEREINANDER,_OM_ZU_OM_B)_APRS-MESSAGEN_(CALL_HALLO_WIR_SIND_AUF_KURS_270_GRAD_73_ROLF)_C)_APRS-EMAIL_(DK4XI_QPSKMAIL.DE_SIND_GUT_ANGEKOMMEN_73_ROLF)")); // NOI18N
        cboMainEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMainEntryActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText(bundle.getString("SEND")); // NOI18N
        jButton1.setToolTipText(bundle.getString("SENDET_DIE_APRS-EMAILS_UND_-MESSAGEN.")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboMainEntry, 0, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMainEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMessagesLayout = new javax.swing.GroupLayout(pnlMessages);
        pnlMessages.setLayout(pnlMessagesLayout);
        pnlMessagesLayout.setHorizontalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMessagesLayout.setVerticalGroup(
            pnlMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMessagesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlMessages, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        parentlogic.txtMainEntryActionPerformed(evt);
        
        cboMainEntry.insertItemAt(getTxtMainEntry(), 0);
        cboMainEntry.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboMainEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMainEntryActionPerformed
        // TODO add your handling code here:
        //cboMainEntry.addItem(getTxtMainEntry());
        //parentlogic.txtMainEntryActionPerformed(evt);
    }//GEN-LAST:event_cboMainEntryActionPerformed

    public void setStatusLabel(String str) {
        StatusLabel.setText(str);
    }

    public String getStatusLabel() {
        return StatusLabel.getText();
    }

    public void setStatusLabelForeground(Color color) {
        StatusLabel.setForeground(color);
    }
    
    public String getTxtStatus() {
        // REWORK
        //return txtStatus.getText();
        return "";
    }

    public void setTxtStatus(String str) {
        txtStatus.setText(str);
    }

    public String getTxtTraffic() {
        return txtTraffic.getText();
    }

    public void setTxtTraffic(String str) {
        txtTraffic.setText(str);
    }

    public void appendTxtTraffic(String str) {
        txtTraffic.append(str);
    }

    public void appendJTextArea3(String str) {
        jTextArea3.append(str);
    }

    public void setTxtMainEntry(String str) {
        cboMainEntry.setSelectedItem(str);

    }

    public String getTxtMainEntry() {
        try {
            // return cboMainEntry.getSelectedItem().toString();
            return ((JTextField) cboMainEntry.getEditor().getEditorComponent()).getText();
        } catch (Exception e) {
            return "";
        }
    }

    public String getTxtClock() {
        return txtClock.getText();
    }

    public void setTxtClock(String str) {
        txtClock.setText(str);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton TrafficLabel;
    private javax.swing.JComboBox cboMainEntry;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel pnlMessages;
    private javax.swing.JPanel pnlTraffic;
    private javax.swing.JLabel txtClock;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextArea txtTraffic;
    // End of variables declaration//GEN-END:variables

}
