/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerTableDialog.java
 *
 * Created on 03.11.2009, 13:50:25
 */

package javapskmail;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebastian_pohl
 */
public class ServerTableDialog extends javax.swing.JDialog {

    private class ServerTableTableCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int rowIndex,
                int vColIndex) {
            
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, rowIndex, vColIndex);

            if (table.getModel().getValueAt(rowIndex, 3).equals("PSK>APRS random") ||
                    table.getModel().getValueAt(rowIndex, 2).equals("10147,0")) {
                // setForeground(Color.RED);
                c.setForeground(new Color(255, 0, 0));
                Font current = getFont();
                c.setFont(current.deriveFont(Font.BOLD));
            } else {
                c.setForeground(Color.BLACK);
            }

            return c;
            
        }

        @Override
        public void validate() {}
        @Override
        public void revalidate() {}
        @Override
        protected void firePropertyChange(String propertyName, Object oldValue, Object newValue) {}
        @Override
	public void firePropertyChange(String propertyName, boolean oldValue, boolean newValue) {}

    }

    ServerDatabase database;

    /** Creates new form ServerTableDialog */
    public ServerTableDialog(java.awt.Frame parent, boolean modal, ServerDatabase database) {
        super(parent, modal);

        initComponents();

        this.database = database;

        tblServer.setDefaultRenderer(Object.class, new ServerTableTableCellRenderer());

        tblServer.setModel(database.buildTableModel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServer = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnNewRow = new javax.swing.JButton();
        btnDelRow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All frequencies dial (Anzeige) USB 2,4 kHz filter.");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        tblServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblServer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/ServerTableDialog"); // NOI18N
        btnSave.setText(bundle.getString("SAVE")); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(btnSave, gridBagConstraints);

        btnNewRow.setText(bundle.getString("NEW")); // NOI18N
        btnNewRow.setActionCommand("btnNewRow");
        btnNewRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(btnNewRow, gridBagConstraints);

        btnDelRow.setText(bundle.getString("DELETE")); // NOI18N
        btnDelRow.setToolTipText(bundle.getString("DELETES_SELECTED_ROW.")); // NOI18N
        btnDelRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(btnDelRow, gridBagConstraints);

        btnCancel.setText(bundle.getString("CANCEL")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(btnCancel, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        database.saveTableModel(tblServer.getModel());

        this.setVisible(false);

}//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnNewRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRowActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblServer.getModel();
        model.addRow(new Object[] {"", "", "", ""});
    }//GEN-LAST:event_btnNewRowActionPerformed

    private void btnDelRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRowActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model;

        if (tblServer.getModel() instanceof DefaultTableModel) {
            model = (DefaultTableModel) tblServer.getModel();
        } else {
            return;
        }

        int numRows = tblServer.getSelectedRows().length;

        for (int i = 0; i < numRows; i++) {
            model.removeRow(tblServer.getSelectedRow());
        }
        
    }//GEN-LAST:event_btnDelRowActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ServerTableDialog dialog = new ServerTableDialog(new javax.swing.JFrame(), true,
                            new ServerDatabase(new File(Main.serverlistPath)));

                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelRow;
    private javax.swing.JButton btnNewRow;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServer;
    // End of variables declaration//GEN-END:variables

}
