/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WXSetupDialog.java
 *
 * Created on 12.06.2009, 13:57:27
 */

package javapskmail;

/**
 *
 * @author sebastian_pohl
 */
public class WXSetupDialog extends javax.swing.JDialog {

    mainpskmaillogic pskmaillogic;

    /** Creates new form WXSetupDialog */
    public WXSetupDialog(mainpskmaillogic plogic, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pskmaillogic = plogic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnWind = new javax.swing.JSpinner();
        spnSea = new javax.swing.JSpinner();
        spnPressure = new javax.swing.JSpinner();
        spnTemp = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cboWindDir = new javax.swing.JComboBox();
        cboSeaDir = new javax.swing.JComboBox();
        cboWeather = new javax.swing.JComboBox();
        cboAntenna = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        spnPower = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javapskmail/WXSetupDialog"); // NOI18N
        jLabel1.setText(bundle.getString("WX_SETUP")); // NOI18N

        spnWind.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnSea.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(60), Integer.valueOf(1)));

        spnPressure.setModel(new javax.swing.SpinnerNumberModel(1000, 920, 1080, 1));

        spnTemp.setModel(new javax.swing.SpinnerNumberModel(20, -10, 40, 1));

        jLabel2.setText(bundle.getString("WIND(BFT.)")); // NOI18N

        jLabel3.setText(bundle.getString("WIND_DIRECTION")); // NOI18N

        jLabel4.setText(bundle.getString("SEA_(METERS)")); // NOI18N

        jLabel5.setText(bundle.getString("SEA_DIRECTION")); // NOI18N

        jLabel6.setText(bundle.getString("PRESSURE_(HP)")); // NOI18N

        jLabel7.setText(bundle.getString("TEMPERATURE_(C°)")); // NOI18N

        jLabel8.setText(bundle.getString("WEATHER")); // NOI18N

        btnCancel.setText(bundle.getString("CANCEL")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText(bundle.getString("SAVE")); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cboWindDir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW" }));

        cboSeaDir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW" }));

        cboWeather.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "/Clear", "/Cloudy", "/Heavy Clouds", "/Showers", "/Lt rain", "/Rain", "/Hvy rain", "/Fog", "/th.storm" }));

        cboAntenna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "B", "D" }));
        cboAntenna.setToolTipText(bundle.getString("STATIONSANTENNE_V:_VERTIKAL,_B:_ACHTERSTARK,_D:_DIPOL.")); // NOI18N

        jLabel9.setText(bundle.getString("ANTENNA")); // NOI18N

        spnPower.setModel(new javax.swing.SpinnerListModel(new String[] {"5", "10", "20", "50", "100"}));
        spnPower.setToolTipText(bundle.getString("STATIONSLEISTUNG_IN_WATT_(W).")); // NOI18N

        jLabel10.setText(bundle.getString("POWER")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnPower, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboAntenna, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboWeather, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnWind, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnSea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnPressure, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnTemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSeaDir, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboWindDir, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnWind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboWindDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboSeaDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboWeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAntenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
            String mystring ="";
            pskmaillogic.myconfig.setPreference("WX", mystring);
            pskmaillogic.myarq.setBoardWX(mystring);        
        setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (pskmaillogic != null) {
            String mystring;
            pskmaillogic.getParentUI().setBoardWX("/Wind:" + spnWind.getValue() + "," + cboWindDir.getSelectedItem() +
                "/Sea:" + spnSea.getValue() + "," + cboSeaDir.getSelectedItem() +
                "/Hp:" + spnPressure.getValue() + "/T:" + spnTemp.getValue() + cboWeather.getSelectedItem() +
                "/A:" + cboAntenna.getSelectedItem() + "/P:" + spnPower.getValue());
            mystring = pskmaillogic.getParentUI().getBoardWX();
            pskmaillogic.myconfig.setPreference("WX", mystring);
            pskmaillogic.myarq.setBoardWX(mystring);
        }
        setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WXSetupDialog dialog = new WXSetupDialog(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboAntenna;
    private javax.swing.JComboBox cboSeaDir;
    private javax.swing.JComboBox cboWeather;
    private javax.swing.JComboBox cboWindDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnPower;
    private javax.swing.JSpinner spnPressure;
    private javax.swing.JSpinner spnSea;
    private javax.swing.JSpinner spnTemp;
    private javax.swing.JSpinner spnWind;
    // End of variables declaration//GEN-END:variables

}
